# Generated by Django 4.1.5 on 2023-01-18 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_patient_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='patient_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission_patient_account', to='admission.patient'),
            preserve_default=False,
        ),
    ]
