# Generated by Django 4.1.5 on 2023-01-18 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0003_patientadmission_patient_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmission',
            name='patient_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission_patient_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
