# Generated by Django 4.1.5 on 2023-01-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.nursestationbuilder')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.schedulebuilder')),
            ],
        ),
    ]
