# Generated by Django 4.1.5 on 2023-01-18 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rolebuilder_created_by_rolebuilder_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolebuilder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolebuilder',
            name='modified_by',
        ),
    ]
